version: "3.9"

volumes:
  store-balance-data: {}

services:
  db:
    image: postgres:latest
    container_name: product_balance
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - store-balance-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: